In [55]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

### 2023 NBA MVP CANDIDATES

In [56]:
url = 'https://www.nba.com/news/kia-mvp-ladder-jan-21-2022-edition'
html = requests.get(url).content

soup = BeautifulSoup(html)
remove_line = 'Last weekâ€™s ranking'
remove_line2 = 'ET'
remove_line3 = 'The Next Five'

top_five = []
next_five = [] 

for line in soup.find_all("strong")[1:-1]:
    if remove_line not in str(line):
        if remove_line2 not in str(line):
            if remove_line3 not in str(line):
                name_raw = str(line).split(',')[0]
                name_raw = name_raw.split('.')[1]
                name = name_raw[1:]
                top_five.append(name)

for line in soup.find_all("p"):
    if 'week: ' in str(line):
        name_raw = str(line).split(',')[0]
        name_raw = name_raw.split('.')[1]
        name = name_raw[1:]
        #name = name.split('>')[1][1:]
        next_five.append(name)
    
top_ten = top_five + next_five

In [57]:
top_ten

['Nikola Jokic',
 'Giannis Antetokounmpo',
 'Joel Embiid',
 'Kevin Durant',
 'Chris Paul',
 'Stephen Curry',
 'DeMar DeRozan',
 'Ja Morant',
 'Rudy Gobert',
 'LeBron James']

In [59]:
url = 'https://www.basketball-reference.com/leagues/NBA_{}_per_game.html'.format(year)
   
r = requests.get(url)
r_html = r.text
soup = BeautifulSoup(r_html,'html.parser')

In [61]:
table=soup.find_all(class_="full_table")
    
""" Extracting List of column names"""
head=soup.find(class_="thead")
column_names_raw=[head.text for item in head][0]
column_names_polished=column_names_raw.replace("\n",",").split(",")[2:-1]
print(column_names_polished)
['Player',
 'Pos',
 'Age',
 'Tm',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

['Player',
 'Pos',
 'Age',
 'Tm',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

In [66]:
players=[]
    
for i in range(len(table)):
        
        player_=[]
        
        for td in table[i].find_all("td"):
            player_.append(td.text)
    
        players.append(player_)
df=pd.DataFrame(players, columns=column_names_polished).set_index("Player")

In [64]:
df.head()

,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Player,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Precious Achiuwa,C,23,TOR,16,0,17.8,2.6,6.8,.376,0.3,2.1,.147,2.3,4.7,.480,.399,1.8,2.2,.829,1.6,4.0,5.6,1.2,0.2,0.7,1.0,1.3,7.3
Steven Adams,C,29,MEM,36,36,26.9,3.6,6.2,.578,0.0,0.0,.000,3.6,6.2,.581,.578,1.0,3.0,.327,4.9,6.3,11.3,2.2,0.9,1.1,1.9,2.3,8.1
Bam Adebayo,C,25,MIA,37,37,35.2,8.5,15.8,.538,0.0,0.3,.100,8.5,15.5,.546,.539,4.4,5.4,.806,2.8,7.1,9.9,3.1,1.1,0.8,2.9,3.0,21.4
Ochai Agbaji,SG,22,UTA,20,0,9.7,1.4,2.9,.483,0.6,1.7,.364,0.8,1.3,.640,.586,0.3,0.5,.500,0.4,0.7,1.1,0.2,0.1,0.0,0.1,1.0,3.7
Santi Aldama,PF,22,MEM,37,16,22.6,3.4,7.1,.479,1.3,3.5,.367,2.1,3.6,.586,.569,1.4,1.9,.732,1.2,3.8,5.0,1.3,0.7,0.8,0.6,2.2,9.4

['Nikola Jokic',
 'Giannis Antetokounmpo',
 'Joel Embiid',
 'Kevin Durant',
 'Chris Paul',
 'Stephen Curry',
 'DeMar DeRozan',
 'Ja Morant',
 'Rudy Gobert',
 'LeBron James']

In [50]:
career = playercareerstats.PlayerCareerStats(player_id='203999') 
season_avg = playercareerstats.PlayerCareerStats(player_id='203999') 
season_avg.get_data_frames()[0].tail(1)

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
7,203999,2022-23,00,1610612743,DEN,27.0,37,37,1238.0,347,563,0.616,33,88,0.375,198,242,0.818,75,324,399,359,53,22,127,102,925